### ISSUE TITLE
Need to save latitude and longitude for map

### ISSUE THREAD

**Issue by camtheman256** [camtheman256/6.1040-final-project#19]
We need to save the latitude and longitude from the PlaceResult, which is contained in PlaceResult.geometry: https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceResult.geometry

https://github.com/camtheman256/6.1040-final-project/blob/88006896b58141570537ee8dc6a73760e8aadbc4/backend/space/collection.ts#L6-L25

**Comment by jasyyang** [comment]
this issue should be resolved following #27
