### ISSUE TITLE
Photos are not pulled in automatically

### ISSUE THREAD

**Issue by camtheman256** [camtheman256/6.1040-final-project#23]
Getting photos requires calling `getUrl()` on a PlacePhoto: https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacePhoto

We also pay a bit more to get photos: https://developers.google.com/maps/billing-and-pricing/pricing#places-photo

**Comment by jas-yang** [comment]
[#https://github.com/camtheman256/6.1040-final-project/blob/12af706127b38bcc54367e44c195e00af64389cf/backend/space/util.ts#L36](https://github.com/camtheman256/6.1040-final-project/blob/12af706127b38bcc54367e44c195e00af64389cf/backend/space/util.ts#L36)

Going to keep this on for now, PlaceRequestResponse should have working photos granted typings is figured out

**Comment by camtheman256** [comment]
Fixed in 51fc71c
