### ISSUE TITLE
No place_id param in path in OpenAPI

### ISSUE THREAD

**Issue by camtheman256** [camtheman256/6.1040-final-project#24]
The OpenAPI docs mention an optional place_id param in the path, but this param is not specified in the path.
<img width="778" alt="Screenshot 2022-12-04 at 12 42 02" src="https://user-images.githubusercontent.com/7855233/205506614-8280e5ff-1d9a-4ad5-8b02-1bd50f92e1cc.png">

https://github.com/camtheman256/6.1040-final-project/blob/e7207edc2e555065e2e71a380f4e802cc8bb7da6/docs/paths/spaces.yml#L47-L55

**Comment by camtheman256** [comment]
I was able to fix this in wire-requests by adding an optional `:place_id?` param that I think was implied:
https://github.com/camtheman256/6.1040-final-project/blob/f0d3dff4ab260af37ec2618493ea869dba208a49/backend/space/router.ts#L51-L55

**Comment by jasyyang** [comment]
ah yes, feel free to merge those changes in ty!
