### ISSUE TITLE
What should author be on a request?

### ISSUE THREAD

**Issue by camtheman256** [camtheman256/6.1040-final-project#25]
We don't have access to the gapi token anymore, because we trade that in for a user object. I'd propose that we store a `Types.ObjectId` here with the User's mongo id, because we do have that, and we can `.populate('author')` to get the full user object if we want.

https://github.com/camtheman256/6.1040-final-project/blob/f0d3dff4ab260af37ec2618493ea869dba208a49/backend/request/model.ts#L6

**Comment by camtheman256** [comment]
For now, I'm just going to store the user's name under author, because that's more human readable

**Comment by jasyyang** [comment]
instead of the gapi access token, they provide us with their own version of identifier which i've been using as the main id for anything user related. 
[link](https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint)

using TokenPayload.sub attribute:
` /**
     * An identifier for the user, unique among all Google accounts and never
     * reused. A Google account can have multiple emails at different points in
     * time, but the sub value is never changed. Use sub within your application
     * as the unique-identifier key for the user.
     */
    sub: string;`
so author = payload.sub, sorry for the confusion

**Comment by camtheman256** [comment]
ok that makes sense! We may want a readable version of the gapi user id to identify posts, but that can be a separate request or get bundled somehow else with the PlaceRequestResponse

**Comment by jasyyang** [comment]
yea, it would be nice to just do `.populate` if we used mongo _id (should have thought of that sooner), but i think for now it would be easier to just do a 
separate GET /user with the gapi user id on the frontend.
