### ISSUE TITLE
Need to populate spaces and users on some requests

### ISSUE THREAD

**Issue by camtheman256** [camtheman256/6.1040-final-project#39]
Would be nice to have populated data for:
- [x] space data for "my requests"
- [x] space data for "today's checkin"
- [x] user data for "checkin counts for a space"
- [x] checkin count on spaces for "all spaces"
- [x] PlaceRequest creation doesn't return a populated response

**Comment by jas-yang** [comment]
- PlaceRequest creation doesn't return a populated response currenty

**Comment by camtheman256** [comment]
PlaceRequest creation doesn’t need to return a populated response if you don’t want because I think we refresh the entire list after a space gets created
