### ISSUE TITLE
Yesterday check-in behavior

### ISSUE THREAD

**Issue by camtheman256** [camtheman256/6.1040-final-project#40]
For `yesterdayCheckIn`, don't we need to filter by `user` here (and possibly alse `space`) to see how many times the user has checked in in total (or for just that space)? I'm confused on what this count is for, because right now it seems like it's just going to get the total # of checkins.

Also another idea for `count` without fetching any documents is you could filter by `user` (and optionally also `space`) and then just check the number of documents returned and then add 1 to that number.

https://github.com/camtheman256/6.1040-final-project/blob/f3a0274616a38b62653ab0235b1d98d1b7bf4f9f/backend/checkin/collection.ts#L13

**Comment by jasyyang** [comment]
yes thank you for catching that we need to filter by `user` for `yesterdayCheckIn`. 
I envisioned count = nth check-in that this check-in object represents for this user at this space.
For example, if i have 
`checkin = {user: '1111', space: '2222', count: 50}` then the creation of this checkin object denotes the 50th checkin that user 1111 had for space 2222. There would be 49 other checkin objects with the same user/space, but counts from 1 ... up to 49. I thought this way of storing "count" would save me some computation time in the future but filtering and counting the number of documents seems easier. 

If the explanation above still doesn't make sense, let me know and I will change the model and filter/count like you mentioned so it makes more intuitive sense.
