### ISSUE TITLE
Getting requests doesn't work when signed out

### ISSUE THREAD

**Issue by camtheman256** [camtheman256/6.1040-final-project#43]
Requests on SingleSpaceView page returns a 403 when a user isn't signed out. Example is https://ourspace-project.vercel.app/space/ChIJ6zsrhqpw44kRc_I9xX7DhwQ. I assume we want signed out users to be able to view requests on a space, so maybe we want to open up this endpoint.

https://github.com/camtheman256/6.1040-final-project/blob/5c45752024c77fb94f9e9b13b499b6c68c3d28a1/src/views/SingleSpaceView.vue#L31

**Comment by jasyyang** [comment]
[this](https://github.com/camtheman256/6.1040-final-project/pull/45/commits/e503407d64ef883b45d2e255515119878f4846e6) commit in #45 should address this
