### ISSUE TITLE
Times are UTC

### ISSUE THREAD

**Issue by camtheman256** [camtheman256/6.1040-final-project#44]
Right now, we're rendering times on the server, which on Vercel is in UTC:
https://github.com/camtheman256/6.1040-final-project/blob/412816ead526e3b839e511aaa259a7d5e9e00141/backend/checkin/util.ts#L35

IMO, this is bad practice, if we send something like `isoFormat()` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString), we can use `Date.parse()` on the frontend and then use `toLocaleString` to get the time string in the right time zone for the user's browser.

**Comment by jasyyang** [comment]
[510d1c7](https://github.com/camtheman256/6.1040-final-project/pull/45/commits/510d1c74f2c1f2d406cf50c1de123b8beae413ec) in #45
